spring:
    application:
        name: api-gateway
    datasource:
        url: ${DB_URL:jdbc:postgresql://localhost:5432/postgres}
        username: ${DB_USERNAME:postgres}
        password: ${DB_PASSWORD:postgres}
        driver-class-name: org.postgresql.Driver
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: none
    config:
        import: optional:file:.env[.properties],optional:file:../.env[.properties]
    cloud:
        gateway:
            server:
                webmvc:
                    routes:
                        - id: portfolio-investments
                          uri: http://localhost:8082
                          predicates:
                            - Path=/v1/investments/**
                          filters:
                            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin Access-Control-Allow-Methods Access-Control-Allow-Headers Access-Control-Expose-Headers, RETAIN_FIRST

                        - id: portfolio-securities
                          uri: http://localhost:8082
                          predicates:
                            - Path=/v1/securities/**
                          filters:
                            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin Access-Control-Allow-Methods Access-Control-Allow-Headers Access-Control-Expose-Headers, RETAIN_FIRST

                        - id: portfolio-holdings
                          uri: http://localhost:8082
                          predicates:
                            - Path=/v1/holdings/**
                          filters:
                            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin Access-Control-Allow-Methods Access-Control-Allow-Headers Access-Control-Expose-Headers, RETAIN_FIRST

                    globalcors:
                        cors-configurations:
                            '[/**]':
                                allowedOrigins:
                                    - "http://localhost:4200"
                                    - "http://127.0.0.1:5500"
                                    - "https://d13to6rck5cj2.cloudfront.net"
                                    - "https://d1jcki4jtvzqdz.cloudfront.net"
                                allowedMethods:
                                    - GET
                                    - POST
                                    - PUT
                                    - DELETE
                                    - OPTIONS
                                allowedHeaders: "*"
                                allowCredentials: true

server:
    port: 8125
    servlet:
        session:
            cookie:
                same-site: none
                secure: true

eureka:
    client:
        fetch-registry: true
        register-with-eureka: true
        service-url:
            default-zone: http://localhost:8761/eureka/
        registry-fetch-interval-seconds: 5
    instance:
        hostname: localhost
        ip-address: 127.0.0.1
        prefer-ip-address: true
        instance-id: ${spring.application.name}:${server.port}
        leaseRenewalIntervalInSeconds: 10
